# Generated by Django 4.0.5 on 2022-08-18 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_city_geocode'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city'),
        ),
        migrations.CreateModel(
            name='Weather24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('geo_code', models.CharField(blank=True, max_length=200, null=True)),
                ('index', models.CharField(blank=True, max_length=200, null=True)),
                ('cloud_cover', models.FloatField(blank=True, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=200, null=True)),
                ('day_or_night', models.CharField(blank=True, max_length=200, null=True)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('icon_code', models.CharField(blank=True, max_length=200, null=True)),
                ('icon_code_extend', models.CharField(blank=True, max_length=200, null=True)),
                ('precip_chance', models.FloatField(blank=True, null=True)),
                ('precip_type', models.CharField(blank=True, max_length=200, null=True)),
                ('pressure_mean_sea_level', models.FloatField(blank=True, null=True)),
                ('qpf', models.FloatField(blank=True, null=True)),
                ('qpf_snow', models.FloatField(blank=True, null=True)),
                ('relative_humidity', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('temperature_dew_point', models.FloatField(blank=True, null=True)),
                ('temperature_feels_like', models.FloatField(blank=True, null=True)),
                ('temperature_heat_index', models.FloatField(blank=True, null=True)),
                ('temperature_wind_chill', models.FloatField(blank=True, null=True)),
                ('uv_description', models.CharField(blank=True, max_length=200, null=True)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('valid_time_local', models.DateTimeField(blank=True, null=True)),
                ('valid_time_utc', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.FloatField(blank=True, null=True)),
                ('wind_direction_cardinal', models.CharField(blank=True, max_length=200, null=True)),
                ('wind_gust', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wx_phrase_long', models.CharField(blank=True, max_length=200, null=True)),
                ('wx_phrase_short', models.CharField(blank=True, max_length=200, null=True)),
                ('wx_severity', models.IntegerField(blank=True, null=True)),
                ('ceiling', models.CharField(blank=True, max_length=200, null=True)),
                ('scattered_cloud_base_height', models.CharField(blank=True, max_length=200, null=True)),
                ('pressure_altimeter', models.CharField(blank=True, max_length=200, null=True)),
                ('qpf_ice', models.CharField(blank=True, max_length=200, null=True)),
                ('qualifier_set', models.CharField(blank=True, max_length=200, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('block', models.IntegerField(blank=True, null=True)),
                ('state_code', models.CharField(blank=True, max_length=200, null=True)),
                ('date_int', models.DateField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.state')),
            ],
        ),
    ]
