# Generated by Django 4.1.1 on 2022-09-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_weather_city_weather24'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corr_dates',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
