# Generated by Django 3.2.15 on 2022-11-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_ensemble'),
    ]

    operations = [
        migrations.CreateModel(
            name='Up_scada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
