# Generated by Django 3.2.15 on 2022-12-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_up_scada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual_demands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('block', models.IntegerField(blank=True, null=True)),
                ('demand', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
