# Generated by Django 4.0.5 on 2022-08-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this item is active.', verbose_name='active status')),
                ('city', models.CharField(default='00', max_length=50)),
                ('state_zone', models.CharField(default='00', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
